In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import MissingIndicator,SimpleImputer

In [15]:
df = pd.read_excel('train.xlsx',usecols=['Age','Fare','Survived'])


In [4]:
df.head()


Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [16]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [17]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)


In [7]:
X_train.head()


Age     Fare
30   40.0  27.7208
10    4.0  16.7000
873  47.0   9.0000
182   9.0  31.3875
876  20.0   9.8458

In [18]:
si = SimpleImputer()
X_train_trf = si.fit_transform(X_train)
X_test_trf = si.transform(X_test)

In [19]:
X_train_trf


array([[ 40.        ,  27.7208    ],
       [  4.        ,  16.7       ],
       [ 47.        ,   9.        ],
       ...,
       [ 71.        ,  49.5042    ],
       [ 29.78590426, 221.7792    ],
       [ 29.78590426,  25.925     ]])

In [20]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf,y_train)

y_pred = clf.predict(X_test_trf)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.6145251396648045

In [21]:
mi = MissingIndicator()

mi.fit(X_train)

MissingIndicator(error_on_new=True, features='missing-only', missing_values=nan,
                 sparse='auto')

In [22]:
mi.features_

array([0], dtype=int64)

In [23]:
X_train_missing = mi.transform(X_train)


In [24]:
X_train_missing


array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [25]:
X_test_missing = mi.transform(X_test)


In [26]:
X_test_missing


array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [27]:
X_train['Age_NA'] = X_train_missing


C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [28]:
X_test


Age      Fare
707  42.0   26.2875
37   21.0    8.0500
615  24.0   65.0000
169  28.0   56.4958
68   17.0    7.9250
606  30.0    7.8958
630  80.0   30.0000
785  25.0    7.2500
660  50.0  133.6500
728  25.0   26.0000
20   35.0   26.0000
486  35.0   90.0000
15   55.0   16.0000
692   NaN   56.4958
643   NaN   56.4958
192  19.0    7.8542
65    NaN   15.2458
597  49.0    0.0000
702  18.0   14.4542
280  65.0    7.7500
505  18.0  108.9000
128   NaN   22.3583
333  16.0   18.0000
402  21.0    9.8250
143  19.0    6.7500
172   1.0   11.1333
458  50.0   10.5000
137  37.0   53.1000
355  28.0    9.5000
317  54.0   14.0000
..    ...       ...
417  18.0   13.0000
62   45.0   83.4750
18   31.0   18.0000
814  30.5    8.0500
197  42.0    8.4042
198   NaN    7.7500
663  36.0    7.4958
447  34.0   26.5500
496  54.0   78.2667
22   15.0    8.0292
267  25.0    7.7750
889  26.0   30.0000
444   NaN    8.1125
372  19.0    8.0500
455  29.0    7.8958
887  19.0   30.0000
412  33.0   90.0000
595  36.0   24.1500
107   NaN    7.7750
258  35.0  512.3292
212  22.0    7.2500
639   NaN   16.1000
786  18.0    7.4958
426  28.0   26.0000
376  22.0    7.2500
89   24.0    8.0500
80   22.0    9.0000
846   NaN   69.5500
870  26.0    7.8958
251  29.0   10.4625

[179 rows x 2 columns]

In [29]:
X_test['Age_NA'] = X_test_missing


C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [30]:
X_train


Age      Fare  Age_NA
30   40.00   27.7208   False
10    4.00   16.7000   False
873  47.00    9.0000   False
182   9.00   31.3875   False
876  20.00    9.8458   False
213  30.00   13.0000   False
157  30.00    8.0500   False
780  13.00    7.2292   False
572  36.00   26.3875   False
77     NaN    8.0500    True
439  31.00   10.5000   False
1    38.00   71.2833   False
175  18.00    7.8542   False
868    NaN    9.5000    True
484  25.00   91.0792   False
248  37.00   52.5542   False
677  18.00    9.8417   False
4    35.00    8.0500   False
397  46.00   26.0000   False
116  70.50    7.7500   False
645  48.00   76.7292   False
463  48.00   13.0000   False
600  24.00   27.0000   False
174  56.00   30.6958   False
582  54.00   26.0000   False
334    NaN  133.6500    True
71   16.00   46.9000   False
202  34.00    6.4958   False
295    NaN   27.7208    True
818  43.00    6.4500   False
..     ...       ...     ...
550  17.00  110.8833   False
359    NaN    7.8792    True
51   21.00    7.8000   False
772  57.00   10.5000   False
102  21.00   77.2875   False
195  58.00  146.5208   False
679  36.00  512.3292   False
805  31.00    7.7750   False
628  26.00    7.8958   False
124  54.00   77.2875   False
404  20.00    8.6625   False
730  29.00  211.3375   False
287  22.00    7.8958   False
831   0.83   18.7500   False
47     NaN    7.7500    True
725  20.00    8.6625   False
587  60.00   79.2000   False
607  27.00   30.5000   False
433  17.00    7.1250   False
674    NaN    0.0000    True
263  40.00    0.0000   False
360  40.00   27.9000   False
75   25.00    7.6500   False
466    NaN    0.0000    True
299  50.00  247.5208   False
534  30.00    8.6625   False
584    NaN    8.7125    True
493  71.00   49.5042   False
527    NaN  221.7792    True
168    NaN   25.9250    True

[712 rows x 3 columns]

In [31]:
si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [32]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf2,y_train)

y_pred = clf.predict(X_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.6312849162011173

In [33]:
#2nd technique
# if you use pandas then use missing indicator class use karna padega
# if you have use sklearn then use turn on this parameter add_indicator = True directly

si = SimpleImputer(add_indicator=True)  # here we can use directly by without missing indicator 


In [34]:
X_train = si.fit_transform(X_train)


In [35]:
X_test = si.transform(X_test)


In [36]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf2,y_train)

y_pred = clf.predict(X_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.6312849162011173